---
name: KOTH-Signs
author: Jackthehack21
version: 1.0.0-Beta1
api:
  - 3.0.0
main: Jackthehack21\KOTH_Signs\Main

depend: [KOTH]
#extensions: [sqlite3]

permissions:
  kothsigns:
    default: false
    description: "All permissions for KOTH-Signs extension."
    children:
      kothsigns.use:
        description: "Allows player to interact with the signs."
        default: true
      kothsigns.add:
        description: "Allows player to create a sign."
        default: op
      kothsigns.rem:
        description: "Allows player to remove a sign."
        default: op
...